export const LANGUAGES: any = {
	zh: {
		timeFormat: {
			today: "今天",
			yesterday: "昨天",
			unitsecond: "秒",
			unitminute: "分",
			unithour: "点",
			unithalfOur: "点半",
			unitoclock: "点整",
			unitday: "号",
			unitdayst: "号",
			unitdaynd: "号",
			unitdayrd: "号",
			thisMonth: "这个月",
			nextMonth: "上个月",
			January: "一月份",
			February: "二月份",
			March: "三月份",
			April: "四月份",
			May: "五月份",
			June: "六月份",
			July: "七月份",
			August: "八月份",
			September: "九月份",
			October: "十月份",
			November: "十一月份",
			December: "十二月份",
			year: "年",
			thisyear: "今年",
			lastyear: "去年",
			oneMin: "1分钟",
			twoMin: "2分钟",
			threeMin: "3分钟",
			fiveMin: "5分钟",
			tenMin: "10分钟",
			fifteenMin: "15分钟",
			halfhour: "半小时",
			oneHour: "1小时",
			oneday: "1天",
			oneWeek: "1周",
			onemonth: "1个月",
			oneYear: "1年",
		},
	},
	en: {
		timeFormat: {
			today: "Today",
			yesterday: "Yesterday",
			unitsecond: "sec",
			unitminute: "min",
			unithour: "",
			unithalfOur: " O'clock past half",
			unitoclock: " O'clock",
			unitday: "th",
			unitdayst: "st",
			unitdaynd: "nd",
			unitdayrd: "rd",
			thisMonth: "This month",
			nextMonth: "Last month",
			January: "Jan",
			February: "Feb",
			March: "Mar",
			April: "Apr",
			May: "May",
			June: "Jun",
			July: "Jul",
			August: "Aug",
			September: "Sep",
			October: "Oct",
			November: "Nov",
			December: "Dec",
			year: "",
			thisyear: "This year",
			lastyear: "Last year",
			oneMin: "1 Minute",
			twoMin: "2 Minute",
			threeMin: "3 Minute",
			fiveMin: "5 Minute",
			tenMin: "10 Minute",
			fifteenMin: "15 Minute",
			halfhour: "Half Hour",
			oneHour: "One Hour",
			oneday: "One Day",
			oneWeek: "One Week",
			onemonth: "One Month",
			oneYear: "One Year",
		},
	},
};
